### ISSUE TITLE
get_incident output as CSV 

### ISSUE THREAD

**Issue by gthieleb** [greenpau/pycherwell#13]
# Steps to reproduce

```
cherwell-client --get-incident 71394 --format csv
```

# Current behvior

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/cherwell/bin/cherwell-client", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/user/pycherwell/cherwell-client", line 122, in <module>
    main()
  File "/home/user/pycherwell/cherwell-client", line 115, in main
    args.output.write(data)
TypeError: write() argument must be str, not dict
```

**Comment by greenpau** [comment]
@gthieleb , I am working on it right now.

**Comment by gthieleb** [comment]
@greenpau Is there a usecase on your side to support export CSV in context of this library?

I am just asking because it would require to flatten the structure of dictionary list (`fields` key) and multiline text. This may break the resulting csv and needs some special handling.

**Comment by greenpau** [comment]
@gthieleb , I added https://github.com/greenpau/pycherwell/commit/031566c3f9eafdd6c1cbb186fb7066ec4f105bb1 . Please see whether this is what you had in mind.

> I am just asking because it would require to flatten the structure of dictionary list (fields key) and multiline text. This may break the resulting csv and needs some special handling.

I think the library should return list of lists (matrix). Then, the code implementing the library, .e.g `cherwell-client`, would choose how to handle the data.

Right now, I just retrieve the value of `value` key in a BO ... and that's it.
