### ISSUE TITLE
get-incidents is missing method

### ISSUE THREAD

**Issue by gthieleb** [greenpau/pycherwell#4]
The method `--get-incidents` is currently is not implemented.

```
cherwell-client --get-incidents
Traceback (most recent call last):
  File "/home/user/.virtualenvs/cherwell/bin/cherwell-client", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/user/pycherwell/cherwell-client", line 122, in <module>
    main()
  File "/home/user/pycherwell/cherwell-client", line 105, in main
    data = cli.get_incidents(opts)
AttributeError: 'CherwellClient' object has no attribute 'get_incidents'
```

It would be great to get an overview of all incidents.

**Comment by greenpau** [comment]
> It would be great to get an overview of all incidents.

@gthieleb , this is work in progress. Will keep this open.

**Comment by greenpau** [comment]
@gthieleb , if you think about other methods, please let me know. I would say a GitHub issue per method. It is pretty straightforward to extend it. I don't always have time.

**Comment by gthieleb** [comment]
Is there some update on this? 

I've seen some progress in branch `getincidents` but specific to this issue.
I started on my in own using `searches_get_quick_search_specific_results_v1` but currently stuck on the neccessary attributes of the search request.

**Comment by greenpau** [comment]
> Is there some update on this?

@gthieleb , not at the moment. I am planning to come back to it next week.

**Comment by greenpau** [comment]
>  I started on my in own using searches_get_quick_search_specific_results_v1 but currently stuck on the neccessary attributes of the search request.

@gthieleb , I actually worked on it recently. Please see https://github.com/greenpau/pycherwell/pull/14

From my perspective, the first step is to pull out information about the teams. That is in the PR already. The next step is pulling info about categories and sub-categories. That is todo. Get incidents have to be filtered in one way of another. That's why I will be adding filter/condition type arguments.

**Comment by gthieleb** [comment]
Hi @greenpau thanks for your update. 

Can you shortly explain what info you need for your specific usecase from `teams` and from `categories`? Is your goal to perform filtering on the API (DB) or on the library level?

Is `get_quick_search...` ok for you or do you focus on another call?

**Comment by greenpau** [comment]
> Can you shortly explain what info you need for your specific usecase from teams and from categories? Is your goal to perform filtering on the API (DB) or on the library level?

@gthieleb , the API method are part of the library already. Get incidents may result in 10000+ entries for a big organization. Thus, it would be reasonable to create a filtering for "get_incidents()" such that it only pull a specific team (queue) or a specific category for incidents. It will be an option that you will pass to "get_incidents()".

> Is get_quick_search... ok for you or do you focus on another call?

@gthieleb, I know that quick search pulls info from multiple places. I am being mindful on the impact of the queries on the overall performance of the system. I will take a look at `get_quick_search()`. Thank you for bringing this to my attention! 😄
